# Generated by Django 3.2.5 on 2021-10-01 08:26

import django.core.validators
from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='amount',
            field=models.IntegerField(verbose_name='قیمت (به تومان)'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان گارانتی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت (به تومان)'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(verbose_name='متن نظر (یا دیدگاه)'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگزاری تصویر'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(upload_to=shop.utils.product_image_path, verbose_name='بارگزاری تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام محصول موردنظر'),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='rate_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز'),
        ),
    ]
