# Generated by Django 3.2.5 on 2021-09-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cهای مجصولات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات کلی محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس\u200cهای محصولات'},
        ),
    ]
