# Generated by Django 3.2.5 on 2021-10-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20211001_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='دسته بندی پدر'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='product.product', verbose_name='محصول موردنظر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.Color', verbose_name='رنگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.ProductMedia', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نظر دهنده'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول موردنظر'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', to='product.Product', verbose_name='محصولات موردنظر'),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده'),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='product.product', verbose_name='محصول موردنظر'),
        ),
    ]
