# Generated by Django 3.2.5 on 2021-09-18 20:50

from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210918_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='media',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(default='', upload_to=shop.utils.product_media_path),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video',
            field=models.FileField(default='', upload_to=shop.utils.product_media_path),
        ),
    ]
