# Generated by Django 3.2.5 on 2021-09-18 23:12

from django.db import migrations, models
import django.db.models.deletion
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210919_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.AddField(
            model_name='guarantee',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(null=True, related_name='products', to='product.Color'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(upload_to=shop.utils.product_media_path),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='video',
            field=models.FileField(upload_to=shop.utils.product_media_path),
        ),
    ]
