# Generated by Django 3.2.5 on 2021-10-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211001_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='عنوان گارانتی'),
        ),
    ]
