# Generated by Django 3.2.5 on 2021-09-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210919_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.Color'),
        ),
    ]
