# Generated by Django 3.2.5 on 2021-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='exact_address',
            field=models.TextField(verbose_name='آدرس دقیق'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=20, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(null=True, verbose_name='کدپستی'),
        ),
    ]
