# Generated by Django 3.2.5 on 2021-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=15, verbose_name='last name'),
        ),
    ]
