# Generated by Django 3.2.5 on 2021-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کدپستی'),
        ),
    ]
