# Generated by Django 3.2.5 on 2021-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=200, verbose_name='استان'),
        ),
    ]
