# Generated by Django 3.2.5 on 2021-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customer_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'این شماره قبلا توسط کاربری دیگر ثبت شده\u200cاست.'}, help_text='شماره موبایل خود را وارد کنید. مثال:09123456789', max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
