# Generated by Django 3.2.5 on 2021-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210922_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(error_messages={'unique': 'این ایمیل قبلا توسط کاربری دیگر ثبت شده\u200cاست.'}, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
