# Generated by Django 3.2.5 on 2021-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(error_messages={'required': 'شماره موبایل وارد نشده!', 'unique': 'این شماره قبلا توسط کاربری دیگر ثبت شده\u200cاست.'}, help_text='شماره موبایل خود را وارد کنید. مثال:09123456789', max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
