# Generated by Django 3.2.5 on 2021-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(help_text='شماره موبایل خود را وارد کنید. مثال:09123456789', max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
