# Generated by Django 3.2.5 on 2021-09-10 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('shipping', models.CharField(choices=[('پیشتاز', 'پیشتاز'), ('سفارشی', 'سفارشی')], default='سفارشی', max_length=10)),
                ('status', models.CharField(choices=[('انصراف', 'انصراف'), ('فعال', 'فعال'), ('انبار', 'پرداخت موفق و درحال بارگیری از انبار'), ('پیک', 'درحال ارسال توسط پیک'), ('تحویل', 'تحویل سفارش به مشتری')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('موفق', 'موفق'), ('ناموفق', 'ناموفق')], max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product')),
            ],
        ),
    ]
