# Generated by Django 3.2.5 on 2021-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='-', max_length=50, verbose_name='رنگ'),
        ),
    ]
