# Generated by Django 3.2.5 on 2021-10-01 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211001_1156'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('پیشتاز', 'پیشتاز'), ('سفارشی', 'سفارشی')], default='سفارشی', max_length=10, verbose_name='نوع پست'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('انصراف', 'انصراف'), ('فعال', 'فعال'), ('بارگیری', 'پرداخت موفق و درحال بارگیری از انبار'), ('پیک', 'درحال ارسال توسط پیک'), ('تحویل', 'تحویل سفارش به مشتری')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
    ]
