# Generated by Django 3.2.5 on 2021-10-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20211001_1156'),
        ('product', '0003_auto_20211001_1249'),
        ('order', '0002_auto_20211001_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='customers',
            field=models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران موردنظر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.address', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product', verbose_name='محصول'),
        ),
    ]
