# Generated by Django 3.2.5 on 2021-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211001_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('پیشتاز', 'پیشتاز'), ('سفارشی', 'سفارشی')], max_length=10, verbose_name='نوع پست'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('انصراف', 'انصراف'), ('فعال', 'فعال'), ('بارگیری', 'پرداخت موفق و درحال بارگیری از انبار'), ('پیک', 'درحال ارسال توسط پیک'), ('تحویل', 'تحویل سفارش به مشتری')], default='بارگیری', max_length=20, verbose_name='وضعیت'),
        ),
    ]
